version: 2.1
jobs:
  build:
    working_directory: ~/knowlg-portal
    machine:
      image: circleci/node:14.21.1-browsers
    steps:
      - checkout:
          path: ~/knowlg-portal
      - run:
          name: Node version
          command: 'node --version'
      - run:
          name: Installing Angular cli
          command: 'npm install -g @angular/cli@14.2.10 --no-progress'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing NPM deps
          command: 'npm install --no-progress'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: ./node_modules
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Building
          command: 'mkdir -p /tmp/logs && node --max_old_space_size=6000 ./node_modules/@angular/cli/bin/ng build --configuration production --optimization=false  | tee /tmp/logs/build.log'
      - run:
          name: Testing
          command: 'npm run test-coverage | tee /tmp/logs/test_cases.log'
      - run:
          name: Install sonar scanner
          command: npm install -g sonarqube-scanner
      - run:
          name: Run sonar scanner
          command: 'cd ~/knowlg-portal && sonar-scanner'
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build

